http:
  middlewares:
    security-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        customResponseHeaders:
          X-Frame-Options: "DENY"
          X-Content-Type-Options: "nosniff"
          Referrer-Policy: "strict-origin-when-cross-origin"
          Permissions-Policy: "geolocation=(), microphone=(), camera=()"
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true

    rate-limit:
      rateLimit:
        burst: 100
        average: 50

    auth:
      basicAuth:
        users:
          - "admin:$2y$05$..."

    cors:
      cors:
        allowCredentials: true
        allowHeaders:
          - "Content-Type"
          - "Authorization"
        allowMethods:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"
        allowOriginList:
          - "https://mjoln1r.com"
        maxAge: 86400