- Apps:
    - Jellyfin:
        href: http://{{HOMEPAGE_VAR_HOST_LAN}}:8096
        icon: jellyfin.png
        description: Media streaming
        ping: http://jellyfin:8096
    - Plex:
        href: https://app.plex.tv/desktop
        icon: plex.png
        description: Media streaming
        ping: http://{{HOMEPAGE_VAR_HOST_LAN}}:32400
        widget:
          type: plex
          url: http://{{HOMEPAGE_VAR_HOST_LAN}}:32400
          key: "{{HOMEPAGE_VAR_PLEX_TOKEN}}"
          fields:
            - streams
            - movies
            - tv
    - Overseerr:
        href: http://{{HOMEPAGE_VAR_HOST_LAN}}:5155
        icon: overseerr.png
        ping: http://overseerr:5055
    - Prowlarr:
        href: http://{{HOMEPAGE_VAR_HOST_LAN}}:9696
        icon: prowlarr.png
        ping: http://prowlarr:9696
    - Sonarr:
        href: http://{{HOMEPAGE_VAR_HOST_LAN}}:8989
        icon: sonarr.png
        description: TV Indexer
        ping: http://sonarr:8989
        widget:
          type: sonarr
          url: http://sonarr:8989
          key: "{{HOMEPAGE_VAR_SONARR_API_KEY}}"
    - Radarr:
        href: http://{{HOMEPAGE_VAR_HOST_LAN}}:7878
        icon: radarr.png
        description: Movie Indexer
        ping: http://radarr:7878
        widget:
          type: radarr
          url: http://radarr:7878
          key: "{{HOMEPAGE_VAR_RADARR_API_KEY}}"

- Downloads:
    - SABnzbd:
        href: http://{{HOMEPAGE_VAR_HOST_LAN}}:8080
        icon: sabnzbd.png
        widget:
          type: sabnzbd
          url: http://sabnzbd:8080
          key: "{{HOMEPAGE_VAR_SAB_API_KEY}}"

- Monitoring:
    - Grafana:
        href: http://{{HOMEPAGE_VAR_HOST_LAN}}:3001/d/system_overview?orgId=1
        icon: grafana.png
        widget:
          type: grafana
          version: 2
          url: http://grafana:3000
          username: "{{HOMEPAGE_VAR_GRAFANA_USERNAME}}"
          password: "{{HOMEPAGE_VAR_GRAFANA_PASSWORD}}"
          fields:
            - dashboards
            - datasources
            - totalalerts
            - alertstriggered
    - Tautulli (Plex Streams):
        href: http://{{HOMEPAGE_VAR_HOST_LAN}}:8181
        icon: tautulli.png
        widget:
          type: tautulli
          url: http://tautulli:8181
          key: "{{HOMEPAGE_VAR_TAUTULLI_API_KEY}}"
          enableUser: true
          showEpisodeNumber: true
          expandOneStreamToTwoRows: false
    - Homepage Status:
        href: http://{{HOMEPAGE_VAR_HOST_LAN}}:3001/d/homepage_status?orgId=1
        icon: grafana.png
    - Prometheus:
        href: http://{{HOMEPAGE_VAR_HOST_LAN}}:9090
        icon: prometheus.png
    - Dozzle (Logs):
        href: http://{{HOMEPAGE_VAR_HOST_LAN}}:9999
        icon: docker.png

- Files:
    - File Browser:
        href: http://{{HOMEPAGE_VAR_HOST_LAN}}:8081
        icon: filebrowser.png
        description: Browse server file structure
        ping: http://filebrowser:80
