name: Repository Maintenance Checks

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  maintenance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install maintenance dependencies
        run: |
          python -m pip install --upgrade pip
          pip install trufflehog

      - name: Run maintenance checks
        run: |
          bash scripts/run-maintenance-checks.sh
